import type { Metadata } from 'next'
import '../../styles/global.scss'
import Script from "next/script";
import React from "react";


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" />
    <body>{children}</body>
    </html>
  )
}
